---
title: "data-analysis"
author: "Rachel Wellington"
date: "10/15/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## TFCB 2018 Homework 2, Problem 8: Analysis of Data from `data/` Folder 

```{r}
data <- read_tsv( "../data/example_dataset_2.tsv") %>%
  print()
```

```{r}
data <- data %>%
  mutate(mean_ratio = mean_yfp / mean_rfp) %>% 
  print()
```

```{r}
data %>%
  mutate(mean_ratio = round(mean_ratio, 2)) %>% 
  print()
```

```{r}
annotations <- read_tsv("../data/example_dataset_3.tsv") %>% 
  print()
```

```{r}
data %>%
  inner_join(annotations, by = "strain") %>% 
  print()
```

```{r}
data %>%
  summarize(max_yfp = max(mean_yfp),
            max_rfp = max(mean_rfp)) %>%
  print()
```

```{r}
data2 <- read_tsv("../data/example_dataset_4.tsv") %>% 
  print(n = 10)
```

```{r}
data2 %>% 
  group_by(strain) %>% 
  print(n = 10)
```

```{r}
data2 %>%
  group_by(strain) %>%
  summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp)) %>% 
  print()
```


```{r}
data2 %>%
  group_by(strain) %>%
  summarize(mean_yfp = mean(yfp), mean_rfp = mean(rfp)) %>% 
  mutate(mean_ratio = mean_yfp / mean_rfp) %>% 
  left_join(annotations, by = "strain") %>%
  ggplot(aes(x = kozak_region, y = mean_ratio,
             color = insert_sequence, group = insert_sequence)) +
  geom_line() +
  geom_point()
```

